name: PokeArch CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x detekt

      - name: Execute Detekt
        run: ./gradlew detekt
        continue-on-error: true

      - name: Execute KtLint
        run: ./gradlew ktlintCheck

      - name: Execute Unit tests
        run: ./gradlew testDebugUnitTest
